openapi: 3.0.0
servers: []
info:
  description: 'Api to create, consult and answer questions in a generic forum'
  version: 1.0.0
  title: Forum api
  termsOfService: ''
  contact:
    email: daniel.lima.nascimento@gmail.com
    name: Daniel Lima do Nascimento
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags: []
paths:
  /questions:
    post:
      tags:
        - question
      summary: Add new question to forum
      description: Method to add new question to forum
      operationId: addQuestion
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema: {}
        '400':
          description: Bad request
          content:
            application/json:
              schema: {}
      security: []
      requestBody:
        $ref: '#/components/requestBodies/Question'
      
    get:
      summary: 'Get all questions '
      description: ''
      parameters: []
      operationId: getAllQuestions
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema: {}
      tags:
        - questions
  /answer:
    post:
      summary: Add answer to a question
      description: ''
      requestBody:
        $ref: '#/components/requestBodies/Answer'
      
      operationId: addAnswer
      responses:
        '200':
          description: Susscess
          content:
            application/json:
              schema: {}
        '400':
          description: Bad request
          content:
            application/json:
              schema: {}
      tags:
        - answers
components:
  schemas: {}
  requestBodies:
    Question:
      content:
        application/json:
          schema:
            type: object
            required:
              - text
              - user
            properties:
              text:
                type: string
                example: My question is...
              user:
                type: string
                example: ze_ninguem
              answers:
                type: array
                items:
                  type: string
            
        
      
      description: Cadastro de perguntas
      required: true
    Answer:
      content:
        application/json:
          schema:
            type: object
            required:
              - parent_id
              - text
              - user
            properties:
              parent_id:
                type: number
                example: 99
              text:
                type: string
                example: My answer is...
              user:
                type: string
                example: ze_ninguem
            
        
      
      description: Cadastro de respostas
      required: true
    
  securitySchemes: {}
  links: {}
  callbacks: {}
security: []
